services:
  - type: web
    name: sistema-inventario-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://aws-0-us-east-1.pooler.supabase.com:6543/postgres?sslmode=require
      - key: DATABASE_USERNAME
        value: postgres.ygznguviubojlbanpqqi
      - key: DATABASE_PASSWORD
        value: DashaControl2026!
      - key: JPA_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_PROFILES_ACTIVE
        value: prod


