services:
  - type: web
    name: sistema-inventario-backend
    runtime: docker
    dockerfilePath: backend/Dockerfile
    dockerContext: backend
    region: oregon
    plan: free
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://db.ygznguviubojlbanpqqi.supabase.co:5432/postgres
      - key: DATABASE_USERNAME
        value: postgres
      - key: DATABASE_PASSWORD
        value: DashaControl2026!
      - key: JPA_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect
      - key: SPRING_PROFILES_ACTIVE
        value: prod


